language: generic

branches:
  only:
    - master

env:
 global:
   - GH_REF: github.com/zwcn/zwcn.github.io

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.74.1/hugo_0.74.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - git submodule update --init --recursive

script:
  - hugo

after_script:
  - cd ./public
  - git init
  - git config user.name "zwcn"
  - git config user.email "zilongwang61@gmail.com"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master
